apiVersion: v1
kind: Pod
metadata:
  name: my-fastapi-app
spec:
  containers:
  - name: my-fastapi-app
    image: article_analyzer
    imagePullPolicy: Never
    resources:
      limits:
        memory: "200Mi"
